<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textarea_notepad</name>
   <tag></tag>
   <elementGuidId>b7c0dcbd-a5ff-44f9-a89b-d8aba59f4683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div[2]/div[13]/div[2]/div[2]/div[1]/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@class = 'ace_text-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ace_text-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>opacity: 0; height: 15px; width: 8.15px; left: 46px; top: 0px;</value>
   </webElementProperties>
</WebElementEntity>
